# List of MVPortal names that should allow entity-teleporting
enabled-portals:
  -

# The time in seconds that a portal should stay open for entities
# after the button has been pressed
time-to-keep-portal-open-for-entities: 30

# Color of the particles that indicate entities can currently
# go through the portal (in RGB format)
particle-color: '0xFF00FF'

# Percentage higher than 0 that determines how many particles
# an activated portal should show
particle-amount: 20