main: io.github.ithotl.entityteleport.Main
name: EntityTeleport
api-version: 1.19
version: 1.0-SNAPSHOT
depend:
  - Multiverse-Core
  - Multiverse-Portals
commands:
  entityteleport:
    aliases:
      - et
    usage: "/entityteleport reload"
    description: reloads the config settings from file
    permission: entityteleport.reload
permissions:
  entityteleport:
    default: op